// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInitialized() {
  return window['go']['main']['App']['CheckInitialized']();
}

export function CreateCodex(arg1, arg2) {
  return window['go']['main']['App']['CreateCodex'](arg1, arg2);
}

export function CreateSection(arg1, arg2) {
  return window['go']['main']['App']['CreateSection'](arg1, arg2);
}

export function DeleteCodex(arg1) {
  return window['go']['main']['App']['DeleteCodex'](arg1);
}

export function DeleteSection(arg1) {
  return window['go']['main']['App']['DeleteSection'](arg1);
}

export function DisconnectGitHub() {
  return window['go']['main']['App']['DisconnectGitHub']();
}

export function GetAllCodexes() {
  return window['go']['main']['App']['GetAllCodexes']();
}

export function GetCodexProgress(arg1) {
  return window['go']['main']['App']['GetCodexProgress'](arg1);
}

export function GetCodexWithSections(arg1) {
  return window['go']['main']['App']['GetCodexWithSections'](arg1);
}

export function GetDefaultContentPath() {
  return window['go']['main']['App']['GetDefaultContentPath']();
}

export function GetGitHubStatus() {
  return window['go']['main']['App']['GetGitHubStatus']();
}

export function GetSectionContent(arg1) {
  return window['go']['main']['App']['GetSectionContent'](arg1);
}

export function GetSectionsByCodex(arg1) {
  return window['go']['main']['App']['GetSectionsByCodex'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportMarkdownFile(arg1) {
  return window['go']['main']['App']['ImportMarkdownFile'](arg1);
}

export function InitializeGitHub(arg1, arg2, arg3) {
  return window['go']['main']['App']['InitializeGitHub'](arg1, arg2, arg3);
}

export function PinCodex(arg1, arg2) {
  return window['go']['main']['App']['PinCodex'](arg1, arg2);
}

export function SaveCurrentWindowSize() {
  return window['go']['main']['App']['SaveCurrentWindowSize']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchCodexes(arg1) {
  return window['go']['main']['App']['SearchCodexes'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectMarkdownFile() {
  return window['go']['main']['App']['SelectMarkdownFile']();
}

export function SetSectionComplete(arg1, arg2) {
  return window['go']['main']['App']['SetSectionComplete'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SyncToGitHub(arg1) {
  return window['go']['main']['App']['SyncToGitHub'](arg1);
}

export function TestGitHubConnection(arg1, arg2) {
  return window['go']['main']['App']['TestGitHubConnection'](arg1, arg2);
}

export function UpdateCodex(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCodex'](arg1, arg2, arg3);
}

export function UpdateSection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSection'](arg1, arg2, arg3);
}
