// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckInitialized():Promise<boolean>;

export function CreateCodex(arg1:string,arg2:string):Promise<models.Codex>;

export function CreateSection(arg1:number,arg2:string):Promise<models.Section>;

export function DeleteCodex(arg1:number):Promise<void>;

export function DeleteSection(arg1:number):Promise<void>;

export function GetAllCodexes():Promise<Array<models.Codex>>;

export function GetCodexProgress(arg1:number):Promise<models.CodexProgress>;

export function GetCodexWithSections(arg1:number):Promise<models.CodexWithSections>;

export function GetDefaultContentPath():Promise<string>;

export function GetSectionContent(arg1:number):Promise<string>;

export function GetSectionsByCodex(arg1:number):Promise<Array<models.Section>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSettings():Promise<Record<string, string>>;

export function ImportMarkdownFile(arg1:string):Promise<string>;

export function PinCodex(arg1:number,arg2:boolean):Promise<void>;

export function SaveSettings(arg1:Record<string, string>):Promise<void>;

export function SearchCodexes(arg1:string):Promise<Array<models.Codex>>;

export function SelectDirectory():Promise<string>;

export function SelectMarkdownFile():Promise<string>;

export function SetSectionComplete(arg1:number,arg2:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateCodex(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateSection(arg1:number,arg2:string,arg3:string):Promise<void>;
